name: kt
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: go
        env:
          KEY_11: ${{ secrets.KEY_11 }}
          KEY_12: ${{ secrets.KEY_12 }}
        run: python kat_test.py
